### PR TITLE
Unregister DeprecationHandler on shutdown

### PR DESCRIPTION
**Pull request by jderusse**
Alternative to https://github.com/ekino/EkinoNewRelicBundle/pull/208

### CODE REVIEW

**Comment by Nyholm** [comment]
Ping @ruudk

**Comment by ruudk** [comment]
I looked into the `shutdown` method of the Bundle but that's only called when you reboot the kernel. Not on shutdown of the kernel.

**Comment by ruudk** [comment]
I think it makes more sense to listen to the `kernel.terminate` event and then remove the listener. I will try to make a PR.

**Comment by Nyholm** [comment]
Thank you

**Comment by ruudk** [comment]
See https://github.com/ekino/EkinoNewRelicBundle/pull/210

**Comment by ruudk** [comment]
Let's merge this as its a good change.

**Comment by jderusse** [comment]
Thank you for the review @ruudk

**Pull request merged**
