### PR TITLE
Bump dev version

### LINKED ISSUE #94: Version bump
I'd like to know what is the criteria to decide to do release a new version, and when is the next one estimated to be released :)

### PR DESCRIPTION
**Pull request by odolbeau**
Fix #94

### CODE REVIEW

**Comment by odolbeau** [comment]
Good for you @rande ?

**Comment by odolbeau** [comment]
I'll create the tag once merged btw

**Comment by rande** [comment]
do we need a new minor version ? or just a patch one ?

**Comment by rande** [comment]
See change: https://github.com/ekino/EkinoNewRelicBundle/compare/1.2.3...HEAD

**Comment by odolbeau** [comment]
I hesitated a lot but I increased the minor version due to the change in the available configuration. :)

I can simply change the patch version if you prefer. :)

**Comment by rande** [comment]
You get the response then ;)

**Comment by odolbeau** [comment]
:+1:

**Pull request merged**
