### PR TITLE
Get default licence and appname from php.ini

### PR DESCRIPTION
**Pull request by EmmanuelVella**
Read ``license_key`` and ``application_name`` from php.ini by default. This allow to  let these values empty in the project config.

### CODE REVIEW

**Comment by blaugueux** [comment]
+1

**Comment by odolbeau** [comment]
Hi.

I don't understand the point of this changement.
By default when you don't set these parameters, all metrics sent to NR use the default ones found in the `php.ini`.

With this modification when you prepare your application on a server which don't have the same values in the php.ini, the deployed code will use this one instead of the application_name defined in the `php.ini` on the server.

Is there of use case which need to have these default parameters?

**Comment by EmmanuelVella** [comment]
I add this because in my case, using the default from ``php.ini`` didn't work. Maybe it's fixed now ?

**Comment by EmmanuelVella** [comment]
I think I find why : https://docs.newrelic.com/docs/agents/php-agent/configuration/php-agent-api#api-set-appname

Newrelic api method signature is ``function newrelic_set_appname (string $name, string $license = ini_get('newrelic.license'), bool $xmit = false): bool``

However, before this PR, the bundle passes``null`` as key so the ``string $license = ini_get('newrelic.license')`` default was overriden.

I think the issue comes from here, and this PR was not the best way to fix it.

**Comment by odolbeau** [comment]
Make sense. :)
It's a bit late so, for now, we just use the previous commit. :)
I'll try to find some time later to find a better way to handle this.

Anyway, thanks for your reactivity. ;)

**Comment by EmmanuelVella** [comment]
You're welcome, I'm going to submit another PR to fix this ;)

**Comment by tristanbes** [comment]
I don't think so since my `application_name` is `null`, and in your check it would default to value from php.ini.

I really don't know why I loose 99% of my stats when both application names are set in the php ini and the bundle though...

**Pull request merged**
