### PR TITLE
Excluded tests from classmap

### PR DESCRIPTION
**Pull request by samnela**

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. It sounds like a good idea. But you need to use autoload-dev to include the tests in "dev"

**Comment by samnela** [comment]
Hello @Nyholm, It's done   but  correct me if it's wrong,  PHPUnit  discover and run the tests by recursively traversing the test directory so  it does not need  autoload-dev .
e.g: https://github.com/symfony/monolog-bundle/blob/master/composer.json#L31

**Comment by jderusse** [comment]
I fixed tests in #213 could you, please, rebase your PR ?

**Comment by samnela** [comment]
I just rebase,  all checks have passed, thank you

**Comment by jderusse** [comment]
Thank you @samnela

**Pull request merged**
