### PR TITLE
Removed Twig deprecated features.

### PR DESCRIPTION
**Pull request by blaugueux**
This PR should solve #97

### CODE REVIEW

**Comment by magnusnordlander** [comment]
Twig functions aren't deprecated, changing this to a filter is a BC break, and doesn't really make much sense.

**Comment by blaugueux** [comment]
I can change Filter to Function if it's ok for you?

**Comment by blaugueux** [comment]
ping @odolbeau

**Comment by odolbeau** [comment]
Seems good for me, thanks for your contribution. :+1:

**Comment by blaugueux** [comment]
Thk ;)

**Comment by angelsk** [comment]
Could we tag a new release for this soon so my profile stops yelling at me :) Thanks!

**Comment by blaugueux** [comment]
+1 :)

**Comment by odolbeau** [comment]
Version 1.3.1 tagged. :)

**Comment by angelsk** [comment]
Probably a stupid question - but how long until my composer update picks up the new version? Thanks

**Pull request merged**
