### PR TITLE
WIP: Switch to fluent services

### PR DESCRIPTION
**Pull request by jderusse**
I also use this PR to alos refactor decorators and argument replacement, 
But the major improvement is in services.xml => services.php files

### CODE REVIEW

**Comment by Nyholm** [comment]
Why would we use PHP over XML for configuration?

**Comment by jderusse** [comment]
IDE Autocompletion and readability

```
<service id="Ekino\NewRelicBundle\Listener\CommandListener">
    <tag name="kernel.event_subscriber"/>
</service>

<service class="Ekino\NewRelicBundle\NewRelic\AdaptiveInteractor" public="false">
    <argument type="service" id="Ekino\NewRelicBundle\NewRelic\NewRelicInteractor" />
    <argument type="service" id="Ekino\NewRelicBundle\NewRelic\BlackholeInteractor" />
</service>
```
vs
```
$services
    ->set(CommandListener::class)
        ->tag('kernel.event_subscriber')

    ->set(AdaptiveInteractor::class)
        ->arg('$real', ref(NewRelicInteractor::class))
        ->arg('$fake', ref(BlackholeInteractor::class))
```

**Comment by Nyholm** [comment]
> IDE Autocompletion and readability

Im not convinced. My IDE is able to autocomplete in XML and Yaml. About readability: I have a hard time reading config in PHP. Mostly because I never see it or use it =) I only "use" it when Im writing symfony docs.

**Comment by jderusse** [comment]
Beware, this is not the standard php service declaration. But the new way introduced here https://github.com/symfony/symfony/pull/23834

For autocompletion, I was thinking about constants in arguments

**Comment by Nyholm** [comment]
Im not convinced.. The "auto completion" is only for you when you add definitions, right?

I am very much in favor to #175. That PR will simplify the config and make it easier to read.

**Pull request closed without merging**
